# Generated by Django 3.2.6 on 2024-02-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriviaNight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='number',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
