# Generated by Django 3.2.6 on 2024-02-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriviaNight', '0002_answer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct_numeric',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='game_id',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
