# Generated by Django 3.2.6 on 2024-02-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriviaNight', '0003_auto_20240216_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='round',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
